version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Etc/UTC
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: deps
      include: scope
    groups:
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
      github-actions-minor-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
        patterns:
          - "*"
      github-actions-major:
        applies-to: version-updates
        update-types:
          - major
        patterns:
          - "*"
